### PR TITLE
Include timestamp

### LINKED ISSUE #378: Coverage output file name
Is there a way to set the output file name so that it will include the project name and a timestamp, pretty much as standard unit test trx files? I cannot find any mention of this.

### PR DESCRIPTION
**Pull request by daveMueller**
closes #378

### CODE REVIEW

**Comment by daveMueller** [comment]
Default format:
image

Specified format:
image

**Comment by MarcoRossignoli** [comment]
@daveMueller I think that we should support same switch for msbuild driver(dotnet test) and maybe if possible also for collectors(but here I don't if it's possible change the name).
BTW I'll flag that issue as `Discussion` because I don't know what @tonerdo @petli think about.

For now stop to work on this. Please every time you pick-up something ask on issue if it's a good candidate so I can confirm there if we need further discussion or it's ok work on it.
It's MY FAULT it was marked as up-for-grubs but the discussion wasn't finished yet, sorry and thank's a lot for your great effort on Coverlet!

**Comment by MarcoRossignoli** [comment]
Ah @daveMueller feel free to pick up also non up-for-grabs issue if you want...pick up what you prefer...if it's not marked or is under discussion "ask" if you can pick up and we'll tell you if it makes sense or not!

**Comment by daveMueller** [comment]
> 
> @daveMueller I think that we should support same switch for msbuild driver(dotnet test) and maybe if possible also for collectors(but here I don't if it's possible change the name).
> BTW I'll flag that issue as `Discussion` because I don't know what @tonerdo @petli think about.

@MarcoRossignoli Ok I already thought so but wasn't sure so I only pushed a solution for the  console drivers. Just hit me up when the discussion on the issue is finished :thumbsup:.

**Comment by MarcoRossignoli** [comment]
Close for the moment, we want to move users to collectors so for now we can pause this feat.
We'll reopen if needed
Thank's for your effort here Dave!

**Comment by 1bberto** [comment]
@MarcoRossignoli I do need this feature mate! 😨 
is there a roadmap to publish it?
I would like to use it on my projects ❤️ 🚀

**Comment by MarcoRossignoli** [comment]
We need to undestand if this feat makes sense...at the moment we don't have a lot of 👍(interest) on issue feat and PR, also coverlet is supported on collectors(https://github.com/coverlet-coverage/coverlet#vstest-integration-preferred-due-to-known-issue-supports-only-net-core-application) and we need to investigate if it's possible define a custom file name as output(at the moment we send a default name `coverage.*` to vstest plat). 

We're trying to keep features aligned as possible through drivers(.net tool, collectors,msbuild).

For now add your +1 here https://github.com/coverlet-coverage/coverlet/issues/378 usually we order the new features using thumbs up to scheduler new features.

**Pull request closed without merging**
