### PR TITLE
Add source link filter & code cleanup

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/tonerdo/coverlet/issues/312

Also applied code cleanup suggestions from VS in files that I touched.

### CODE REVIEW

**Comment by tonerdo** [comment]
I'm quite wary of adding too many options for every single edge case. What's the specific reason for this? 

If it's purely to allow choice, then we should consider introducing assembly level attributes that can override specific global coverlet options. Like this source link issue for example

For situations where the source link flag is set, but assemblies you don't own don't have source link information (which I think is the case here). The best solution is simply to update the code to fallback to regular debug information if there's no source link data

**Comment by ViktorHofer** [comment]
I understand your concerns, I don't many options either.

We live build some assemblies in our product and some we just consume. Hence the paths in the pdb of the consumed assemblies can't be used as they point to CI machine's local paths. Currently coverlet only allows using source link for either all or none assemblies. We just want to use source link for the assemblies that we don't live build.

What about if we change the existing option `--use-source-link` to `--source-link-filter` which allows either `all` or a list of assemblies (like in my PR). With that we would keep the number of options sane. I don't think that somebody already relies on the added source link feature so I wouldn't think about a breaking change here.

I don't think attributes on an assembly level is a good idea here as we would need to put them on source assemblies which we ship.

**Comment by tonerdo** [comment]
> For situations where the source link flag is set, but assemblies you don't own don't have source link information (which I think is the case here). The best solution is simply to update the code to fallback to regular debug information if there's no source link data

@ViktorHofer, how about this bit? Do you think it helps your use case?

**Comment by ViktorHofer** [comment]
It's exactly the other way around. We want source link data not to be used for assemblies that we own/build (which in fact do have source link data in them).

Maybe I should question myself why we add source link information when building locally. Let me check with my team and get back to you.

**Comment by ViktorHofer** [comment]
Ok this can be closed as we will just disable sourcelink completely for local builds.

**Pull request closed without merging**
