### PR TITLE
Skip switch symbol tests fail in "release mode"

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
closes https://github.com/tonerdo/coverlet/issues/389
Temporary skip tests in release mode.

/cc @tonerdo @petli

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
@tonerdo I tried to fix checking right line in release but it doesn't work...the issue raise only on Windows/Release

**Comment by MarcoRossignoli** [comment]
I did some test with Ubuntu 18.04 and I get same exception from release config...maybe we should use a different Ubuntu image on appveyor to get consistent behaviour `Ubuntu1804` https://www.appveyor.com/updates/
VS 2019 will be available this month https://github.com/appveyor/ci/issues/2907#issuecomment-488345102

**Comment by MarcoRossignoli** [comment]
Another idea could be avoid to rely on "machine sdks" and download a run build/test with "specific" sdk in a cross way https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script so we would have same "compiler"

**Comment by tonerdo** [comment]
What version of Ubuntu does AppVeyor use by default?

**Comment by MarcoRossignoli** [comment]
We use `Ubuntu` and from AppVeyor docs 
```
Linux images:
Ubuntu or Ubuntu1604 - Ubuntu 16.04
Ubuntu1804 - Ubuntu 18.04
```

**Pull request merged**
