### PR TITLE
[WIP]Fix nightly upload nuget package order

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
Fix nightly upload nuget package order

Now we've order i.e. `coverlet.msbuild.2.6.1-preview-0011-gfbf1f3beb8.nupkg`

cc: @tonerdo

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
@AArnott here https://github.com/tonerdo/coverlet/issues/403#issuecomment-496303004 you said "moving your versioning to a major.minor.height pattern?" but I cannot have this behaviour, in this PR I fixed order issue and I like it we release 3 package with hash and height and after some usage tests I found ok the user experience, clear the order(last master first) and simple way to link with master commit with hash.
Could be also better if we generate something like `coverlet.msbuild.2.6.11-preview-gfbf1f3beb8.nupkg` instead of `coverlet.msbuild.2.6.1-preview-0011-gfbf1f3beb8.nupkg` but `1.0.{height}-preview` schema is not supported, what I'm missing?

**Comment by AArnott** [comment]
> here #403 (comment) you said "moving your versioning to a major.minor.height pattern?" but I cannot have this behaviour,

It's up to you. But I'm a bit confused because later in your above comment it sounds like you're asking for exactly what I had prescribed:

> Could be also better if we generate something like coverlet.msbuild.2.6.11-preview-gfbf1f3beb8.nupkg instead of coverlet.msbuild.2.6.1-preview-0011-gfbf1f3beb8.nupkg

Yes. I'm happy to help you do that.

> but 1.0.{height}-preview schema is not supported, what I'm missing?

That's not the right syntax. Instead, use `1.0-preview`. The `{height}` macro is only used when inside a prerelease tag. Otherwise, the height is implied as the next integer in the version that you haven't specified. So if you specify major.minor, then height goes into PATCH, and if you specify major.minor.patch then height goes into REVISION (4th integer).

**Comment by AArnott** [comment]
Now regarding the `-preview` tag and the hash that you're struggling with... I'm writing up a doc to explain it. I've had to explain it a few times so I figured a doc would save me time down the road.

**Comment by MarcoRossignoli** [comment]
Close and reopen I did a mess with rebase 😞

**Comment by MarcoRossignoli** [comment]
BTW @AArnott seem that works as expected now
image

I'll open a new PR with where I'll publish directly with CI, we'll go on on that thread!

**Comment by MarcoRossignoli** [comment]
> Now regarding the -preview tag and the hash that you're struggling with... I'm writing up a doc to explain it. I've had to explain it a few times so I figured a doc would save me time down the road.

@AArnott point me you doc when done!

**Comment by AArnott** [comment]
Will do. I hope to have it done by EOD.

**Comment by MarcoRossignoli** [comment]
Oh ready for my breakfast :smile:

**Comment by AArnott** [comment]
OK, here is [the first draft](https://github.com/AArnott/Nerdbank.GitVersioning/blob/publicReleaseDoc/doc/public_vs_stable.md). I'd be interested in your feedback and questions before I merge this into master.

**Comment by MarcoRossignoli** [comment]
Doc are very clear...open a draft if you want and I'll review also with some simple advice like newlines

**Comment by AArnott** [comment]
Done: https://github.com/AArnott/Nerdbank.GitVersioning/pull/345

**Pull request closed without merging**
