### PR TITLE
Add support of ExcludeFromCodeCoverage attribute

### LINKED ISSUE #22: Why Coverlet use custom attribute ExcludeFromCoverage instead of ExcludeFromCodeCoverage
Hi guys!

Why Coverlet use the custom attribute `ExcludeFromCoverage` from its own namespace instead of using already exists in .NET Core attribute `ExcludeFromCodeCoverage` from namespace `System.Diagnostics.CodeAnalysis`?

To Coverlet ignore any class, I need to install the nuget package `coverlet.msbuild` in all projects with tests, right?

### PR DESCRIPTION
**Pull request by Valeriy1991**
Resolve #22

### CODE REVIEW

**Comment by tonerdo** [comment]
Hmmm. Merge conflicts still seem to be a problem.

**Comment by azabluda** [comment]
>  Commits 39   Files changed 30

Why is it not just a trivial extension of https://github.com/tonerdo/coverlet/blob/5dac9409016bd1a85e57e82a4c1c5fbdeea34f28/src/coverlet.core/Instrumentation/Instrumenter.cs#L215-L218 backed with a couple of relevant unit tests?

**Comment by TLogik** [comment]
BUMP

**Comment by MarcoRossignoli** [comment]
@Valeriy1991 @tonerdo should we close...seem stale

**Pull request closed without merging**
