### PR TITLE
Index sources into PDBs

### PR DESCRIPTION
**Pull request by AArnott**
Use SourceLink so that debugging into sources is easy.
Also rely on thet .NET SDK to set the RepositoryUrl property. This allows the generated nuspec file to contain the actual commit ID that produced the package.

### CODE REVIEW

**Comment by AArnott** [comment]
The build failure appears to be unrelated and is due to #444

**Comment by AArnott** [comment]
Never mind. It's not unrelated. The build failure is due to the the new snupkg symbols package being somehow empty.

**Comment by AArnott** [comment]
> how to "step into" code in case of issue using one of our way to instrument:

I do it by adding a check for an unlikely environment variable, then calling Debugger.Launch()

**Comment by MarcoRossignoli** [comment]
> I do it by adding a check for an unlikely environment variable, then calling Debugger.Launch()

So you release with `Debugger.Launch()` under if?I understood well?

**Comment by MarcoRossignoli** [comment]
ping @tonerdo

**Comment by AArnott** [comment]
ping

**Comment by MarcoRossignoli** [comment]
ping @tonerdo

**Pull request merged**
