### PR TITLE
[Bug fix] Put the same code that is in covelet.console to show the same result in 'average'  (tonerdo#346)

### PR DESCRIPTION
**Pull request by dlplenin**
@MarcoRossignoli 
Average calculation: This PR is related with https://github.com/tonerdo/coverlet/pull/479

Today I installed a nightly build of coverlet.msbuild and I realized that a piece of code in coverlet.msbuild.tasks was not taken into account in the previous PR, to keep consistency.

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
For reference:
copied from https://github.com/tonerdo/coverlet/pull/479/files#diff-eb52911939126f43e581b3bd31c276f3 `Program.cs`

**Comment by MarcoRossignoli** [comment]
@dlplenin Diego can you try tomorrow and confirm correct output please?

**Comment by dlplenin** [comment]
> @dlplenin Diego can you try tomorrow and confirm correct output please?

Monday for sure! Now I dont have my computer with me, sorry. 
I'll keep u posted.

**Comment by MarcoRossignoli** [comment]
Oh yes I mean "tomorrow" we'll have new nighly...when you can 😄

**Comment by dlplenin** [comment]
@MarcoRossignoli 
It's working as expected! Thanks 👍

Running a docker compose:
docker-compose-coverage-

**Comment by MarcoRossignoli** [comment]
Thank's to you for help!

**Pull request merged**
