### PR TITLE
Try to fix netstandard.dll hell

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
Fixes https://github.com/tonerdo/coverlet/issues/340

Explanation of problem is on issue and on cecil repo https://github.com/jbevain/cecil/issues/575

I ask to @Frankwayne and @eMarkM to kindly clone and try this branch if possible and provide in case some feedback!

@Frankwayne your repro now works, you need to skip xunit `dotnet test -l trx --filter Category!=Integration /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /v:n /p:Exclude=\"[Dapper*]*,[xunit*]*\"`

/cc @tonerdo @petli and @ViktorHofer to understand if this behaviour could break coreclr/corefx coverage.

### CODE REVIEW

**Comment by eMarkM** [comment]
I will try to pick this up within the next week.  Thanks for all your help!

**Comment by tonerdo** [comment]
@MarcoRossignoli kindly fix the conflicts and I'll merge this. Heads up @ViktorHofer, will this affect corefx builds?

**Comment by MarcoRossignoli** [comment]
@tonerdo conflicts resolved

**Comment by MarcoRossignoli** [comment]
@ViktorHofer please review this

**Comment by MarcoRossignoli** [comment]
ping @ViktorHofer

**Comment by ViktorHofer** [comment]
This could indeed break corefx. Let me test the change locally today. I'll get back to you.

**Comment by MarcoRossignoli** [comment]
thank's @ViktorHofer

**Comment by ViktorHofer** [comment]
Just validated. Coverage measurement still works fine with CoreLib after this change.

**Comment by MarcoRossignoli** [comment]
@tonerdo we can merge ok by @ViktorHofer

**Pull request merged**
