### PR TITLE
Add System.Private.CoreLib support

### PR DESCRIPTION
**Pull request by pjanotti**
This is a special case needed to make coverlet the official code coverage tool on CoreFx repo (see https://github.com/dotnet/corefx/issues/31281).

The change didn't cause any noticeable performance penalty and basically has a custom "metada importer processor" to deal with System.Private.CoreLib.

### CODE REVIEW

**Comment by tonerdo** [comment]
@pjanotti don't worry about the coverage result right now. I don't enforce a threshold and 94% is still pretty good! Will review this PR over the weekend

**Comment by ViktorHofer** [comment]
@tonerdo have you had time to look into the changes? We really would like to use them in corefx as soon as possible :)

**Comment by pjanotti** [comment]
Good question @tonerdo: the issue is that System.Private.CoreLib can't reference any external assembly and the tracker template is injected, intentionally, by referencing netstandard. This allows it (at least in theory) to instrument assemblies running against any runtime that supports netstandard. All the code used by the tracker template is part of System.Private.CoreLib so what this change does is that it ensures that no actual reference is made via netstandard.

Unfortunately I didn't see a way for this special case.

**Comment by tonerdo** [comment]
Thanks for this @pjanotti, will make a new release tomorrow and notify you once that happens

**Pull request merged**
