### PR TITLE
Fix strong name validation failures

### PR DESCRIPTION
**Pull request by sharwell**
This is a prerequisite for coverlet.msbuild.tasks working on .NET Framework (#299).

### CODE REVIEW

**Comment by tonerdo** [comment]
@sharwell I think #286 already took care of this. Did you notice anything missing?

**Comment by ViktorHofer** [comment]
Why do we need the new coverlet templates assembly at all?

**Comment by sharwell** [comment]
@ViktorHofer There will be two copies of coverlet.templates in the NuGet package one way or the other. There doesn't seem to be any drawback to multi-targeting this assembly according to the runtime support.

**Comment by ViktorHofer** [comment]
@tonerdo this is a simple change which resolves the long standing strong name validation errors that we were hitting in coverlet plus it removes a dependency which always nice. Can we get this merged?

**Comment by sharwell** [comment]
> ... plus it removes a dependency …

This was an undesirable side effect of a bug outside control of this repository. I'm going to file a follow-up issue to switch back to using the dependency once the source bug has been resolved.

**Pull request merged**
