### PR TITLE
CalculateCoverage: Fix file not foundexception

### PR DESCRIPTION
**Pull request by sbalant**
Check if the file HitsFilePath exists

--
I have the same issue as https://github.com/tonerdo/coverlet/issues/8
This simple check fix my problem

### CODE REVIEW

**Comment by tonerdo** [comment]
Hi @sbalant, thanks for your contribution. I have some thoughts:

This approach just ignores the problem and it's not obvious to the user that something went wrong. A better approach will be to figure out why that error is even being thrown in the first place and try to prevent that. Possibly the file isn't being created in the first place? (https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/CoverageTracker.cs#L31)

**Comment by sbalant** [comment]
No problem ;)

**Comment by StillLearnin** [comment]
Any idea when this will be released to Nuget. I'm hitting this issue also.

**Comment by StillLearnin** [comment]
Splendid! Thanks!

**Pull request merged**
