### PR TITLE
Fix missing quotation mark for test command

### PR DESCRIPTION
**Pull request by ste1nstone**
Add the missing quotation mark to the test command in the contributing guide

### CODE REVIEW

**Comment by tonerdo** [comment]
@ste1nstone your commit isn't linked to your GitHub profile and your contribution won't get attributed

**Comment by ste1nstone** [comment]
@tonerdo sorry I'm new to github and I thought my commits are linked via the email from commit and github account.
Could you please give me a hint where I can see that my commit isn't linked.
I can't find that information and all answers I find are referencing to an email match.

**Comment by MarcoRossignoli** [comment]
your commit isn't linked to your GitHub profile and your contribution won't get attributed

@tonerdo I don't undestand what you mean...

**Comment by tonerdo** [comment]
@MarcoRossignoli it appears to no longer be an issue

**Pull request merged**
