### PR TITLE
Add total line coverage for badge generators

### PR DESCRIPTION
**Pull request by kolipka**
Should solve #178 and #148 with regex: 
/Total.*?([0-9]{1,3})(,[0-9]{1,2})?%/

### CODE REVIEW

**Comment by pimmerks** [comment]
Might also want to show the average of branch and method coverage like in: #104 & #123
```
Total Line: 100%
Total Branch: 100%
Total Method: 100%
```
Something like this maybe?

**Comment by kolipka** [comment]
no problem :)

**Comment by kolipka** [comment]
C:\projects\coverlet\test\coverlet.core.tests\coverage.opencover.xml'

67 
68 +------------------+--------+--------+--------+
69 | Module | Line | Branch | Method |
70 +------------------+--------+--------+--------+
71 | coverlet.core | 90.8% | 86.2% | 93.4% |
72 +------------------+--------+--------+--------+
73 | coverlet.tracker | 0% | 0% | 0% |
74 +------------------+--------+--------+--------+
75 
76 
77 Total Line 89.7%
78 Total Branch 84.6%
79 Total Method 91.7%

**Comment by Taturevich** [comment]
When this pr will be merged?

**Pull request merged**
