### PR TITLE
Fix for code complexity not being generated for methods for cobertura reporter

### LINKED ISSUE #797: Cyclomatic complexity at method level is missing
I'm trying to generate a report showing the Cyclomatic complexity of my methods, unfortunately the complexity is always empty:
image

In my coverage.cobertura.xml I can see that the complexity is calculated on the class level but not a method level:
```
<class name="<omitted>" filename="<omitted>" line-rate="1" branch-rate="1" complexity="5">
    <methods>
        <method name="<omitted>" signature="(System.Guid)" line-rate="1" branch-rate="1">
```

I was looking through the source code and noticed that in the [CoberturaReporter](https://github.com/NorekZ/coverlet/blob/7258b73d947840348b5ec93f1d5e78ff3782e2a9/src/coverlet.core/Reporters/CoberturaReporter.cs#L69) we're not calculating the complexity and thus the value won't show up.

Is this a bug or is there something else I'm missing?

### PR DESCRIPTION
**Pull request by dannyBies**
Fixes #797 

Please let me know if there are any other tests you want me to add.

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
Can you run a coverage and confirm that complexity is shown(to be sure of attribute name)?

**Comment by dannyBies** [comment]
Below is the document generated by the unit test:

image

The document generated without the fix:
image

**Comment by MarcoRossignoli** [comment]
@dannyBies I'm not sure it cobertura support complexity per method, I don't find any sample with attribute on method.

i.e. https://raw.githubusercontent.com/jenkinsci/cobertura-plugin/master/src/test/resources/hudson/plugins/cobertura/coverage-with-data.xml

Can you find a place/example where that attribute is reported?

**Comment by dannyBies** [comment]
I assumed this would be supported based on https://github.com/cobertura/cobertura/pull/144 . Looks like you have to explicitly enable this functionality using --calculateMethodComplexity. 

I'll see if I can create an example with cobertura tomorrow evening.

**Comment by MarcoRossignoli** [comment]
You can pack and use msbuild package similar to https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#use-local-collectors-build

**Comment by dannyBies** [comment]
I've followed the [guide](https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#use-local-collectors-build) and it seems to be working. I ran ``` dotnet test --collect:"XPlat Code Coverage" ``` to generate the output.

Is there anything else that needs to be done or verified?

Implementation:
```
public class Class1
    {

        public bool IsAdult(int age)
        {
            if (age > 18)
            {
                if (age >100)
                {
                    return false;
                }
                return true;
            }
            return false;
        }
    }
```

Test:
```
public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            Class1 x = new Class1();

            Assert.True(x.IsAdult(88));
        }
    }
```

Generated xml

```
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="0.6666" branch-rate="0.5" version="1.9" timestamp="1586340658" lines-covered="6" lines-valid="9" branches-covered="2" branches-valid="4">
  <sources>
    <source>C:\</source>
  </sources>
  <packages>
    <package name="ClassLibrary1" line-rate="0.6666" branch-rate="0.5" complexity="4">
      <classes>
        <class name="ClassLibrary1.Class1" filename="Users\Danny\source\repos\ClassLibrary1\Class1.cs" line-rate="0.6666" branch-rate="0.5" complexity="4">
          <methods>
            <method name="IsAdult" signature="(System.Int32)" line-rate="0.6666" branch-rate="0.5" complexity="4">
              <lines>
                <line number="9" hits="1" branch="False" />
                <line number="10" hits="1" branch="True" condition-coverage="50% (1/2)">
                  <conditions>
                    <condition number="8" type="jump" coverage="50%" />
                  </conditions>
                </line>
                <line number="11" hits="1" branch="False" />
                <line number="12" hits="1" branch="True" condition-coverage="50% (1/2)">
                  <conditions>
                    <condition number="18" type="jump" coverage="50%" />
                  </conditions>
                </line>
                <line number="13" hits="0" branch="False" />
                <line number="14" hits="0" branch="False" />
                <line number="16" hits="1" branch="False" />
                <line number="18" hits="0" branch="False" />
                <line number="19" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="9" hits="1" branch="False" />
            <line number="10" hits="1" branch="True" condition-coverage="50% (1/2)">
              <conditions>
                <condition number="8" type="jump" coverage="50%" />
              </conditions>
            </line>
            <line number="11" hits="1" branch="False" />
            <line number="12" hits="1" branch="True" condition-coverage="50% (1/2)">
              <conditions>
                <condition number="18" type="jump" coverage="50%" />
              </conditions>
            </line>
            <line number="13" hits="0" branch="False" />
            <line number="14" hits="0" branch="False" />
            <line number="16" hits="1" branch="False" />
            <line number="18" hits="0" branch="False" />
            <line number="19" hits="1" branch="False" />
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>
```

**Comment by MarcoRossignoli** [comment]
If you load report on tool you shown here https://github.com/tonerdo/coverlet/issues/797#issue-595608024 do you show correct data?

**Comment by dannyBies** [comment]
Yes, it shows the correct data for the cyclomatic complexity, before this change it was "-".

image

**Comment by dannyBies** [comment]
Thanks for taking the time to look at this!

**Comment by MarcoRossignoli** [comment]
Feel free to pick up other issue if you want!Just in case let me know if you're in trouble with debugging/testing.

**Pull request merged**
