### PR TITLE
Fix nightly build versioning

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
@clairernovotny I fixed nightly version.

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
Need to fix integration test to find new version name.

**Comment by clairernovotny** [comment]
@MarcoRossignoli you can see how Rx does integration tests here. We use a multi-stage build where artifacts are published in build and then downloaded on multiple platforms:
https://github.com/dotnet/reactive/blob/master/azure-pipelines.rx.yml

I download the artifacts into a directory and then add/update via the dotnet command:
https://github.com/dotnet/reactive/blob/master/azure-pipelines.rx.yml#L169-L175

In all cases NBGV knows what the version is.

**Comment by MarcoRossignoli** [comment]
Our integration need to check coverage results https://github.com/tonerdo/coverlet/blob/master/test/coverlet.integration.tests/DotnetTool.cs#L30 or for instance https://github.com/tonerdo/coverlet/blob/master/test/coverlet.integration.tests/Collectors.cs not only run coverage.

**Comment by MarcoRossignoli** [comment]
Issue related to long path https://github.com/dotnet/sdk/issues/11244

**Pull request merged**
