### PR TITLE
Add ability to instrument non-referenced assemblies

### PR DESCRIPTION
**Pull request by jherby2k**
As discussed in #192, I want to be able to instrument assemblies that aren't project references (loaded at runtime). I actually have 2 use cases:

1) Instrumenting a PowerShell core binary module (and its references), which gets loaded via System.Management.Automation.Runspaces.InitialSessionState.ImportPSModule.
2) Instrumenting "extensions" discovered at runtime using MEF (System.Composition.Hosting), and loaded via Assembly.LoadFrom.

To accomplish this, I added an "IncludeDirectories" parameter which allows additional paths to be searched for modules. It supports relative and absolute paths, and a wildcard (*) for including one level of subdirectories (useful for MEF extensions).

One side effect is the possibility that one or more assemblies exists in multiple locations. I dealt with this by including a hash of the file path in each backup file name, and then merging the results for all files with the same name after instrumentation.

Example that includes both a bunch of extension subdirectories and the PowerShell.Commands module directory (both relative paths from the project output directory):

`dotnet test --no-build /p:CollectCoverage=true /p:IncludeDirectories="Extensions\*,PowerShell.Commands"`

### CODE REVIEW

**Comment by jherby2k** [comment]
Uhm, those two failing tests seem really spurious - I saw them fail once on my (Windows) desktop too. Not sure it has anything to do with my PR.

**Comment by jherby2k** [comment]
Looks like PR #204 also deals with the merging of files with the same name and different paths.

**Comment by pape77** [comment]
@jhereby2k check #211 i changed it to merge by file name outside the merge method. Adding modules by filename not path anymore in coverage.cs!

**Comment by jherby2k** [comment]
@pape77 That's a nicer solution, so I've reverted the changes I made to CoverageResult.cs in my PR.

**Comment by pape77** [comment]
@jherby2k  nice :) Have you retested with this?

**Comment by jherby2k** [comment]
Of course! It works fine.

**Comment by jherby2k** [comment]
I'm happy to update the readme as well, I just want to confirm this looks good first.

**Comment by jherby2k** [comment]
@pape77 on further testing it does not work fine :(. It merges 2 copies of the same file no problem, but it can't instrument 2 different files with the same name at the same time. So I've reverted to my method, which uses the full path as key and then merges them together at the end. A bit more complicated, but more robust too.

**Comment by pape77** [comment]
@jhereby2k I couldn't quite follow. In the example of my pr i do a dotnet test on a solution that has several test projects.
The scenario there is more than one proj referencing the same dll from different paths. It adds the key by filename the first time and does compare without problems on the following merges with the same filenames bit different paths.
Can you illustrate a bit more when does it not work? Is it just for clacenarios in which you include your extra param to include more files to be merged?

**Comment by jherby2k** [comment]
It’s specific to my PR’s changes. With the IncludeDirectories option, you might end up with two copies of the same file during the same run. Really only one gets loaded into memory, but since you don’t know which will get loaded first, they need to be instrumented separately (so two different keys in the dictionary) and then merged before displaying the results. So my PR always does a merge at the end, and merges any files with the same name.

**Comment by tonerdo** [comment]
@jherby2k kindly fix the merge conflicts so I can review. Thanks!

**Comment by tonerdo** [comment]
Still have some questions regarding merging results but will have a clearer picture once I can make a more wholesome review. Apologies for letting this slide for too long

**Comment by jherby2k** [comment]
@tonerdo No problem! Conflicts resolved. Sorry about all the commits - I had some issues with line endings in Coverage.cs.

**Comment by tonerdo** [comment]
@jherby2k not to worry. I'm trying to wrap my head around your merging logic and trying to figure out if it's indeed needed. Will take a much deeper look after that

**Comment by jherby2k** [comment]
If one of my libraries is a dependency of multiple add-ins/ extensions, it will appear in multiple folders at once, right? And each copy gets instrumented during testing. The merging combines them into a single result. If I don’t merge the result, the dependency gets listed multiple times.

Hope that makes sense.

**Comment by tonerdo** [comment]
@jherby2k just a heads up that this is still on my radar

**Comment by ViktorHofer** [comment]
@jherby2k Please see my PR https://github.com/tonerdo/coverlet/pull/253 which deals with the same issue. Unfortunately I overlooked your PR. If you agree I will incorporate the changes I made in the InstrumentationHelper class into your PR. There's only one problem.

I wanted to avoid having duplicate assembly names at all as that could leave to different issues. My solution is to prioritize the assembly probing:
1. The test assembly's directory.
2. The additional passed in directories as they are passed in.

That allows us in corefx i.e. to use the IL version of System.Private.CoreLib.dll. Means, I need a way to load assembly a from directory A but not load assembly a from directory B.

**Comment by ViktorHofer** [comment]
@jherby2k this feature is fairly time sensitive for us in corefx. It would be great if we could discuss it together with @tonerdo on a channel to get it in as soon as possible. We could either use Gitter, Teams or Skype. Does that work for both of you?

**Comment by jherby2k** [comment]
@ViktorHofer 

> I wanted to avoid having duplicate assembly names at all as that could leave to different issues. My > solution is to prioritize the assembly probing:
>  1. The test assembly's directory.
>  1. The additional passed in directories as they are passed in.

I'm cool with selecting only one in principal, but in practice the above order isn't what I want. I have a binary PowerShell module that depends on and returns types defined in "common.dll". The module exists in its own directory. The test assembly also references "common.dll" because it tests the results returned from that module. But I want the one in the module directory instrumented, not the one in the test directory.

**Comment by jherby2k** [comment]
How about a MergeIdenticalFileNames switch?

**Comment by ViktorHofer** [comment]
Having assemblies with the same assembly and module name isn't support well as it comes with different issues outside of the GAC world. I strongly recommend not going that path...

**Comment by ViktorHofer** [comment]
Opened https://github.com/jherby2k/coverlet/pull/1

**Comment by jherby2k** [comment]
Poorly named option then - not what I intended. How about MergeIdenticalAssemblies? Maybe with an additional check to see if the assemblies really are identical.

**Comment by ViktorHofer** [comment]
> Poorly named option then - not what I intended. How about MergeIdenticalAssemblies? With an additional check to see if the assemblies really are identical.

Can you please explain what identical assemblies are and what they are for? Why do I need to instrument identical assemblies multiple times?

**Comment by jherby2k** [comment]
you don't. As you said, you just need to instrument one of them. But your intended probe order is the opposite of mine. That's why I just instrument them both and then merge the results. Then it doesn't matter which one is actually loaded.

**Comment by ViktorHofer** [comment]
But instrumenting both takes a considerable amount of time and doesn't seem right. If your issue is the priority, why don't we introduce an option to control it?

**Comment by ViktorHofer** [comment]
Sure, let me know if I can help somehow. And sorry to be so pushy to get this feature in but we depend on it in corefx ⚡️

**Comment by ViktorHofer** [comment]
@jherby2k could you accept my PR in the meantime so that @tonerdo can review your PR with my changes? That would be really great. I also noticed that with this work this issue will also be fixed: https://github.com/tonerdo/coverlet/issues/246

**Comment by jherby2k** [comment]
@ViktorHofer Sorry about the unnecessary back and forth - looks like your solution gives the results I want regardless. I've merged your PR and added one extra commit to revert my now-unnecessary backup file naming algorithm.

**Comment by ViktorHofer** [comment]
Your PR seems wrong as it contains all the commits that happened since you opened yours. You probably want to fix that by rebasing or merging or just take my PR where I already did that: https://github.com/tonerdo/coverlet/pull/253

**Comment by jherby2k** [comment]
Blargh, I give up. I'll add my one change to #253.

**Pull request closed without merging**
