### PR TITLE
WIP: Inital support for dotcover.

### PR DESCRIPTION
**Pull request by gilescope**
Might need to rework things as the Teamcity reporter is now a file reporter and a console reporter.
I've not included a service message yet to indicate where the file is so that TeamCity can hover it up.
I couldn't see a way to return two coverage measures in cov.xml so for now the default is branch coverage.

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
> Might need to rework things as the Teamcity reporter is now a file reporter and a console reporter.

Can you open a new issue with some context?Documentation links etc...
So we can keep track of works, you can link this PR using "closes #issuenum"

**Comment by MarcoRossignoli** [comment]
@gilescope do you think to complete this?
Or we can close for the moment and re-open in future?

**Comment by gilescope** [comment]
Best to close - sorry have moved over to the dark side (rust)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MarcoRossignoli** [comment]
> Best to close - sorry have moved over to the dark side (rust)

wow ok...thanks for the answer.

**Pull request closed without merging**
