### PR TITLE
Fix bug: exception filters appear on the wrong line

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
fixes https://github.com/tonerdo/coverlet/issues/278

/cc @tonerdo @petli

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
@hughbe if you've some time can you try this update with your project?I cannot compile, build fail. Step:
1) Clone this branch
2) build package
```
C:\git\coverlet (exceptionfilter -> origin)
λ msbuild /t:CreateNuGetPackage /p:Configuration=Release build.proj
...
Successfully created package 'C:\git\coverlet\build\Release\coverlet.console.1.4.1.nupkg'
```
3) Add Nuget.Config on root of you solution:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="localcoverlet" value="C:\git\coverlet\build\Release" />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

```
and try to restore/test

/cc @pape77

**Comment by MarcoRossignoli** [comment]
> LGTM! Ready to go once you fix up the merge conflicts

It's not a merge issue, it's new github features "draft pr" https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by MarcoRossignoli** [comment]
> Use single :)

Done thank's!

**Comment by tonerdo** [comment]
> It's not a merge issue, it's new github features "draft pr"

Lol, I didn't even read the message but just assumed it was a conflict.

**Comment by MarcoRossignoli** [comment]
@tonerdo no response I think we can go on with this

**Comment by MarcoRossignoli** [comment]
great thank's to @pape77 out best beta tester 😘

**Pull request merged**
