### PR TITLE
Add nuget.config file

### PR DESCRIPTION
**Pull request by AArnott**
Every repo should have this to turn OFF any unauthorized feeds that may be configured machine wide, and to ensure that any custom feeds required are recorded in source control for everyone.

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
cc: @tonerdo can we merge?

**Comment by AArnott** [comment]
ping

**Comment by MarcoRossignoli** [comment]
ping @tonerdo

**Comment by tonerdo** [comment]
Sorry for the delay on this guys. Last few weeks have been quite hectic for me. Working on a schedule

**Pull request merged**
