### PR TITLE
Hide report generator strong name warning

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
We use report generator core to help on debugging, it's not signed, we'll suppress warning at project level.

cc: @tonerdo @danielpalme

### CODE REVIEW

**Comment by danielpalme** [comment]
I will sign ReportGenerator as soon as ImageSharp gets signed (see https://github.com/danielpalme/ReportGenerator/issues/210, https://github.com/SixLabors/ImageSharp/issues/738)

**Comment by MarcoRossignoli** [comment]
> I will sign ReportGenerator as soon as ImageSharp gets signe

Thank's!Keep me updated if you can!

**Comment by danielpalme** [comment]
> > I will sign ReportGenerator as soon as ImageSharp gets signe
> 
> Thank's!Keep me updated if you can!

I will notify you (see https://github.com/danielpalme/ReportGenerator/projects/2#card-20977365).
But I don't know when ImageSharp gets signed.

**Comment by MarcoRossignoli** [comment]
Great thank's!

**Comment by danielpalme** [comment]
I was finally able to sign the ReportGenerator DLLs with a strong name.

Release 4.6.0 contains the changes:
https://www.nuget.org/packages/ReportGenerator/4.6.0
https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/4.6.0
https://www.nuget.org/packages/ReportGenerator.Core/4.6.0

**Comment by MarcoRossignoli** [comment]
Thanks Daniel!

**Pull request merged**
