### PR TITLE
Add support for merging results

### LINKED ISSUE #36: How can I union coverage results in one file?
Hello! 

I have multiple tests projects - one with unit tests and one with integration tests. How can I calculate code coverage for both projects with coverlet?

### PR DESCRIPTION
**Pull request by tonerdo**
Fixes #36

### CODE REVIEW

**Comment by Jenan** [comment]
Could you provide some details how to use this new feature? :)
Thanks

**Comment by tonerdo** [comment]
@Jenan I just updated the README: https://github.com/tonerdo/coverlet#merging-results, https://github.com/tonerdo/coverlet#merging-results-1

**Comment by MortenChristiansen** [comment]
The merge option only works with the native json format. How would I merge results in the cobertura format?

**Comment by MortenChristiansen** [comment]
I got it working by outputting both the cobertura and json formats, though it required me to create a json coverage file containing `{}` first. Otherwise the first project in the solution fails as it has nothing to merge with.

**Comment by tonerdo** [comment]
Merging with non coverlet json formats might not ever be a supported option. It's way more easier with the coverlet json because it's just a serialization of the internal `CoverageResult` object. Other formats require more pre-processing and some information is lost in translation

**Pull request merged**
