### PR TITLE
Allow to prevent RestoreOriginalModule when GetCoverageResult is called

### PR DESCRIPTION
**Pull request by shargon**
There are specific situations when you want to preserve the Instrumentation. For example fuzzing techniques, we are working on an fuzzer using this library for the coverage and we need this change.

Thanks for your amazing work

### CODE REVIEW

**Comment by shargon** [comment]
For prevent the revert after the process die we use this

```csharp

                var helper = (IInstrumentationHelper)DependencyInjection.Current.GetService(typeof(IInstrumentationHelper));

                var field = (ConcurrentDictionary<string, string>)helper
                    .GetType()
                    .GetField("_backupList", BindingFlags.Instance | BindingFlags.NonPublic)
                    .GetValue(helper);

                field.Clear();
```

There are an easier way?

**Comment by MarcoRossignoli** [comment]
Hi @shargon before go on with this we need to re-open discussion with @tonerdo @petli on future of core lib.
As you can see on this PR https://github.com/tonerdo/coverlet/pull/566 we're discussing if has got sense expose a stable "core" functionality lib.
You can read some history on linked issue https://github.com/tonerdo/coverlet/pull/566#issuecomment-536053774 https://github.com/tonerdo/coverlet/issues/212

The issue with this kind of update is that are not "well structured" and "planned". I mean at the moment we don't guarantee core lib types stability(reason for hide everything) so we're concerned about take direct dependency on classes in these assembly.
We could break in future.

My idea was hide all and only public pertinent object through interfaces/factories and be free to update internal implementation.

**Comment by MarcoRossignoli** [comment]
@shargon to view instrumented asm you could use also msbuild https://github.com/tonerdo/coverlet/issues/296#issuecomment-470527068

**Comment by shargon** [comment]
If you don't expose a stable "core" nuget, you are killing some good ideas. Is possible with a fork yes, but have sense to do that?

**Comment by MarcoRossignoli** [comment]
> If you don't expose a stable "core" nuget, you are killing some good ideas

cc: @tonerdo @petli

**Comment by MarcoRossignoli** [comment]
@shargon close this, because we'll start to shape public api.
Until that moment you'll need to clone and add a signature to your asm and adding to friendly asm on core lib. Let me know if you're in trouble.

**Pull request closed without merging**
