### PR TITLE
Issues #29 & #95

### PR DESCRIPTION
**Pull request by StephenMP**
Issues #29 & #95 : Displays the average coverage % for all coverage types

### CODE REVIEW

**Comment by StephenMP** [comment]
Interesting that run two different times, codecov reports two different results...

**Comment by StephenMP** [comment]
Made a benign whitespace change to get the build process to re-run and fix Codecov issues. @tonerdo let me know if there's anything I need to do.

**Comment by tonerdo** [comment]
@StephenMP no need. Will take a look once I get the chance

**Comment by tonerdo** [comment]
Hiya @StephenMP Can I please see a screenshot of the final output. Also, I have my reservations about this feature considering the 2.0 update simply compares each assembly's coverage against the threshold instead of the average coverage

**Comment by StephenMP** [comment]
@tonerdo 

The final output looks like the following
```
Starting test execution, please wait...

  Total tests: 87. Passed: 87. Failed: 0. Skipped: 0.
  Test Run Successful.
  Test execution time: 9.2234 Seconds

  Calculating coverage result...
    Generating report 'path\to\coverage.xml'

  +---------------+--------+--------+--------+
  | Module        | Line   | Branch | Method |
  +---------------+--------+--------+--------+
  | coverlet.core | 90.3%  | 85.5%  | 94.1%  |
  +---------------+--------+--------+--------+

  +---------+--------+--------+--------+
  |         | Line   | Branch | Method |
  +---------+--------+--------+--------+
  | Average | 90.3%  | 85.5%  | 94.1%  |
  +---------+--------+--------+--------+
```

If you have your reservations, that's fine, I was just adding something suggested by two open tickets. If you don't want to include it you can close the pull request and the tickets 😄

**Comment by basilfx** [comment]
I would love to have this averaging feature. 

In my solution I have unit tests and integration tests over multiple projects. Since these tests complement each other, it makes more sense to look at the average coverage, instead of the lowest coverage.

**Pull request merged**
