### PR TITLE
Replace AppVeyor badge with Azure Pipelines

### LINKED ISSUE #416: Update build badge AZP
@tonerdo we need to update build badge on `README.md` I cannot access to "copy link" here I found some guide https://gregorsuttie.com/2019/03/20/azure-devops-add-your-build-status-badges-to-your-wiki/

### PR DESCRIPTION
**Pull request by AArnott**
Closes #416

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
Mmm...I didn't found that but only https://docs.microsoft.com/en-us/rest/api/azure/devops/build/badge/get%20build%20badge%20data?view=azure-devops-rest-5.0
Thank's

**Comment by AArnott** [comment]
FYI: @MarcoRossignoli  You can get the status badge markdown from here:
image

**Comment by tonerdo** [comment]
Will merge after #422

**Comment by tonerdo** [comment]
@AArnott qq: anyway to override using git height for the patch version? I wanna make a new release and it doesn't really have the public release incremented by just one. E.g. `2.6.1` -> `2.6.2`

**Comment by AArnott** [comment]
@tonerdo Your question looks a bit off topic for this PR. This PR just replaces the README badge to reflect that you build on Azure Pipelines now. Wanna open another issue to discuss?

**Comment by tonerdo** [comment]
@AArnott yeah it was just a random question. I thought to ask here since this was an open PR. Nevermind that now, I've figured out what I need to do

**Comment by MarcoRossignoli** [comment]
@AArnott can you resolve so we can merge?

**Comment by AArnott** [comment]
done

**Pull request merged**
